### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by yuedun** [fex-team/yog-log#8]
```
TypeError: Path must be a string. Received undefined
               at assertPath (path.js:7:11)
               at Object.dirname (path.js:1324:5)
               at Module._compile (module.js:565:22)
               at requireFromString (/home/huo/workspace/platform/node_modules/yog-log/index.js:637:7)
               at Object.getLogString (/home/huo/workspace/platform/node_modules/yog-log/index.js:424:40)
               at Object.writeLog (/home/huo/workspace/platform/node_modules/yog-log/index.js:365:24)
               at Object.log (/home/huo/workspace/platform/node_modules/yog-log/index.js:142:22)
               at Object.trace (/home/huo/workspace/platform/node_modules/yog-log/index.js:101:25)
               at Object.trace (/home/huo/workspace/platform/node_modules/node-ral/lib/logger.js:54:39)
               at loadFile (/home/huo/workspace/platform/node_modules/node-ral/lib/ralmodule.js:44:20)
[13:34:35] /home/huo/workspace/platform/node_modules/yog-log/index.js:431
                   return LOGGER_CACHE[format](this, util) + '\n';
                                              ^

           TypeError: LOGGER_CACHE[format] is not a function
               at Object.getLogString (/home/huo/workspace/platform/node_modules/yog-log/index.js:431:36)
               at Object.writeLog (/home/huo/workspace/platform/node_modules/yog-log/index.js:365:24)
               at Object.log (/home/huo/workspace/platform/node_modules/yog-log/index.js:142:22)
               at Object.trace (/home/huo/workspace/platform/node_modules/yog-log/index.js:101:25)
               at Object.trace (/home/huo/workspace/platform/node_modules/node-ral/lib/logger.js:54:39)
               at loadFile (/home/huo/workspace/platform/node_modules/node-ral/lib/ralmodule.js:44:20)
               at Array.map (native)
               at RalModule.load (/home/huo/workspace/platform/node_modules/node-ral/lib/ralmodule.js:70:15)
               at Array.map (native)
               at Function.RAL.init (/home/huo/workspace/platform/node_modules/node-ral/lib/ral.js:389:20)
```

修改yog-log/index.js第424行为LOGGER_CACHE[format] = requireFromString(jsStr,"a");//第二个参数随意
可以正常启动

**Comment by hefangshi** [comment]
已处理
